name: CI
on:
  - push
jobs:
  test:
    name: 🔍 Testing
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: 🎭 Install Playwright
        run: npx playwright install --with-deps
      - name: 📦 Prepare the environment
        run: cp .dev.vars.example .dev.vars
      - name: 💣 Run some tests
        run: npx playwright test

  lint:
    name: ⬣ Linting
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: ✨ Code format check
        run: npx prettier --check .
      - name: ✅ Code linting
        run: npx eslint . --ext .js,.mjs,.ts,.tsx
