name = "remix-cloudflare-template"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [{ binding = "cache", id = "cache" }]

[vars]
GITHUB_OWNER = "edmundhung"
GITHUB_REPO = "remix-cloudflare-template"
